apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 0
  selector:
    matchLabels:
      app: prometheus
template:
  metadata:
    labels:
      app: prometheus
  spec:
    containers:
      - name: local_prometheus
        image: prom/prometheus:latest
